### ISSUE TITLE
Actividad Bonus: Dos Dudas 💫

### ISSUE THREAD

**Issue by SrGarZito** [bellinux/InfoVis2014II#1]
**¡Buenas tardes!**

Contexto: Durante la ayudantía yo pregunte si puedo hacer otro personaje que no sea Pochita, en ese momento me dijeron que sí, pero ahora han formado algunas dudas al respecto:

1.- Uno de los requisitos para la décima +0.1 es que sea Pochita según Canvas, ¿Esto no se rige si yo he hecho otro personaje?
2.- Con respecto al evento, ¿Sirve simplemente un botón con un sonido respectivo al personaje que hice? ¿O se requiere algo más?

_Hint: El personaje es un Pokémon._

♦️♣️ **_¡Saludos cordiales!_** ♠️♥️

**Comment by Sofiasson** [comment]
Si se motivan a hacer a otro personaje, esta permitido pero con criterio. Tiene que tener una dificultad parecida a como es el pochita. Usando las funciones de crear circulo, rectangulo y elipse, y tambien la rotación de un elemento. Además que tenga superposición de elementos.

La elección del evento es totalmente libre, asi que un botón con sonido es válido.

Saludos

**Comment by SrGarZito** [comment]
**¡Excelente!**

Efectivamente, dispongo de al menos 1 de cada tipo de los criterios solicitados en la imagen. Sin embargo, si lo desea, puedo publicar mismamente el dibujo que he realizado en una siguiente consulta para que usted mismo juzgue si cumple con las expectativas o no. De esa manera, se puede garantizar optar por +0.1 de décima.

También he decir, que he cambiado el "Dark-mode" por "Shiny-mode" (Referente al variocolor del Pokémon), se me había olvidado mencionarlo en la primera consulta. ¿Eso es válido? (A mi criterio si, ya que imagino que el trabajo en sí radica en aprender conceptos básicos y variaciones de color a raíz de un botón).


♦️♣️ _**¡Saludos!**_ ♠️♥️

**Comment by Sofiasson** [comment]
Si se demuestra que se pudo implementar los conceptos que se querían abordar en la ayudantía, el bonus se aplicara sin problema

Saludos  ( ͡❛ ͜ʖ ͡❛)👍
