### ISSUE TITLE
Duda sobre Interrogación 1 (P1)

### ISSUE THREAD

**Issue by SVenegasA** [bellinux/InfoVis2014II#2]
Hola!
Perdonen la confusión, pero ¿A qué se refieren las pregunta con que si es que aplica o no algo? ¿Se refiere acaso si es que el punto puede ser asociado al grafico entregado y nosotros solo debemos asociar el punto al gráfico y explicar cómo se relacionan?
Muchas graciaaas

**Comment by bellinux** [comment]
Hola! Si, se refiere a lo que tu dices si entiendo bien. Igual siempre hay que motivar la respuesta. 
Te sugiero ver el ejercicio desarrollado (està el link en la plantilla) para ver el tipo de respuestas que se esperan. Saludos
